### ISSUE TITLE
追加osx的媒体键控制支持

### ISSUE THREAD

**Issue by eNkru** [eNkru/electron-xiami#11]
增加OSX多媒体键盘和Touchbar的支持

**Comment by jinhw1989** [comment]
还有能否支持linux下的快捷键, 下一首 上一首, 暂停/播放

**Comment by eNkru** [comment]
@jinhw1989 问题是我没有多媒体键盘可以测试。你愿意帮我测试一下么？

**Comment by eNkru** [comment]
#20 

添加了多媒体键盘支持 macOS & linux
添加了Touchbar支持 MacBook with Touchbar
