### ISSUE TITLE
在.gitignore文件中添加package-lock.json

### ISSUE THREAD

**Issue by huiyifyj** [eNkru/electron-xiami#18]
如题。
具体原因看下图。
![package-lock.json造成的原因](https://i.loli.net/2018/02/08/5a7be08651bd3.png)

**Comment by eNkru** [comment]
从Repo里删除了package-lock.json文件。其实最近一直在用Yarn，导致package-lock.json是空。

**Comment by huiyifyj** [comment]
哪怕不是空的，我感觉这个也是要放.gitignore里吧。0.0🙃

**Comment by eNkru** [comment]
要不要commit package-lock.json一直有争论。不过我也觉得不用commit lock file。Done
