### ISSUE TITLE
Linux里面软件名改成虾米音乐可好？

### ISSUE THREAD

**Issue by hipkomh** [eNkru/electron-xiami#23]
非常感谢打包了这么精致好用的客户端，体验超级棒~
感觉软件名electron-xiami很不和谐，我手动改成了虾米音乐。能请求换一下不：）

**Comment by eNkru** [comment]
一直在用GNOME，没有完全测试别的桌面。多谢提交

**Comment by eNkru** [comment]
@hipkomh 喜欢的话多给推荐推荐。用的人多了建议就多，软件就会越来越贴心。

**Comment by hipkomh** [comment]
哦哦，有这方面的考虑哈。体验很不错，歌词和精简模式比网易云好用 ~ 赞一个

**Comment by jingle0927** [comment]
可以学其他的github项目 wewechat ieasemusic  

xiaixiami  例如这个 喜爱虾米
