### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by felipealco** [eNkru/electron-xiami#24]
Hello!
There is anyway to change the application language?

If translation is needed I would like to help.

Thanks

**Comment by eNkru** [comment]
Thank you for the support.

The application is a wrapper to enable the official [Xiami Online Player](http://www.xiami.com/play) in Linux & Mac desktop environments. The application provides the default english version and can be changed to Chinese in Settings. However, the player itself doesn't have the english version. If we want to achieve it, we need to use something like "jQuery" to modify the original web page after loaded.

It can be done, but a little bit tricky to do (just like the dekstop lyrics). We will consider it when the demands are higher to make that happen.

**Comment by eNkru** [comment]
@felipealco if you are talking about the application langurage other than English & Chinese, please let me know which language you are familiar and I'll let you know how to do it :)

**Comment by eNkru** [comment]
Let me know if you still need to discuss this :)
