### ISSUE TITLE
如何调用虾米api

### ISSUE THREAD

**Issue by bzvew** [eNkru/electron-xiami#28]
你好，请问是否有空做一个虾米的api呢？

**Comment by eNkru** [comment]
阿里只开放了非常有限的APIs
http://bigdata.taobao.com/docs/api_list.htm?cid=20625

基本上就是排行榜，歌曲搜索和艺人搜索。

如果没有官方的支持，想写API基本上是不可能的事情。任何改动都会导致API不好用。

如果有什么好的想法可以分享一下。网易云音乐好像有私有API，不知道他们怎么作的。有时间我研究一下。

**Comment by eNkru** [comment]
目前没有考虑这个需求。
