### ISSUE TITLE
小细节

### ISSUE THREAD

**Issue by nununull** [eNkru/electron-xiami#3]
点播放不弹窗显示正在播放的歌曲可能更好

**Comment by eNkru** [comment]
切歌的时候会弹出播放歌曲的信息，信息应该会保存在历史消息里。

点击图标弹出主窗口应该是默认的动作吧。

如果支持播放信息的多或许在下个版本会改掉，或者增加设置功能。　（正在考虑增加设置功能）

**Comment by eNkru** [comment]
１．０．３版本增加了设置点击选项
