### ISSUE TITLE
状态栏图标失效

### ISSUE THREAD

**Issue by kid1412621** [eNkru/electron-xiami#30]
![image_2018-04-14_00-18-29](https://user-images.githubusercontent.com/26278054/38746409-f35038e0-3f79-11e8-81cc-36722675daf9.png)

好像electron的问题：https://github.com/electron/electron/issues/9046

Ubuntu 17.10

**Comment by eNkru** [comment]
最新的app用的是electron 1.8.2。这个问题应该被修复了。
如果还有问题你试试

`export XDG_CURRENT_DESKTOP=Unity`

是不是新版本的Unity又出兼容问题了

**Comment by kid1412621** [comment]
是 Gnome 吧

Howard J <notifications@github.com> 于 2018年4月14日周六 08:00写道：

**Comment by eNkru** [comment]
@kid1412621 突然想起一件事情。你是不是有重新设置icon theme？设置icon会覆盖之前的.desktop文件。你试着重新安装一次软件应该可以修复。

**Comment by kid1412621** [comment]
@eNkru 我装了一个图标包，但是实在装软件之前装的，这有影响吗？是不是我重新切换一次图标包就好了？

**Comment by eNkru** [comment]
那应该不是这个原因。electron的软件再重装了软件包之后会失效。我看你还有一个electorn-ssr也没又图标。你用gnome什么版本？我回头看看我用的什么。

**Comment by kid1412621** [comment]
@eNkru 3.26.2

**Comment by RyanZHe** [comment]
18.04 也有类似的问题.
![screenshot from 2018-06-26 14-01-16](https://user-images.githubusercontent.com/16871889/41930610-8fa2be1c-7949-11e8-964d-1a5f09b220de.png)
![screenshot from 2018-06-26 14-01-52](https://user-images.githubusercontent.com/16871889/41930606-8c7e46ac-7949-11e8-8603-c49c67ae6313.png)

**Comment by RyanZHe** [comment]
应该是electron-builder的问题[＠２５７７](https://github.com/electron-userland/electron-builder/issues/2577)．
在package.json中加入`"StartupWMClass": "xiami music"`或在.desktop中加入`StartupWMClass=xiami music`可解决这个问题  #42

**Comment by eNkru** [comment]
@RyanZHe 感谢PULL REQUEST

@kid1412621 你可以测试一下最新的CODE，修复的话可以CLOSE了。

等我有空拿到UBUNTU的测试机，也会测一下。

**Comment by kid1412621** [comment]
@eNkru 
嗯嗯，修复了，我在 18.04 上测的没问题，辛苦了
