### ISSUE TITLE
Any chance to get keyboard shortcuts support?

### ISSUE THREAD

**Issue by zinechant** [eNkru/electron-xiami#34]
I am by no means familiar with the electron frameworks. Is it possible to get global keyboard shortcuts support?

**Comment by zinechant** [comment]
It seems possible from a quick search https://electronjs.org/docs/tutorial/keyboard-shortcuts

**Comment by zinechant** [comment]
Oh, I see there is already Gnome media key support. I am going to close this issue.

**Comment by eNkru** [comment]
it does support the gnome media key, macOS media key and touch bar.
