### ISSUE TITLE
状态栏没有图标，gnome3.28

### ISSUE THREAD

**Issue by Armstrongzcl** [eNkru/electron-xiami#36]
点击关闭后，还在播放，但是没有状态栏图标，无法打开，是gnome问题？还是eletron问题？

**Comment by eNkru** [comment]
有一段逻辑在关掉app之前kill tray。偶尔会有这个问题。
如果不KILL的话，AUTO UPDATE会生成两个TRAY ：（

看看有没有更好的办法

**Comment by eNkru** [comment]
@Armstrongzcl 你是点击退出退出程序，声音还在播放吗？有没什么错误窗口弹出来？

**Comment by Armstrongzcl** [comment]
嗲及 关闭，按钮 桌面端就关闭了，但是声音还在放。没有错误提示、弹窗。

**Comment by eNkru** [comment]
https://github.com/eNkru/electron-xiami/commit/d8fc283b81d8f170a719953069fc1749d9a9fb80

这个应该会FIX之前遇到的托盘的问题 ：）

@Armstrongzcl 如果还有问题，重开这个issue

**Comment by Armstrongzcl** [comment]
最近发现是gnome3.28的问题，挺多应用都没有图标，重启gnome以后图标可以显示出来。虾米程序是没有问题的，抱歉了误报了，谢谢！
