### ISSUE TITLE
在 Mac 上使用 command + Q 关闭应用时程序崩溃

### ISSUE THREAD

**Issue by Kexin-Li** [eNkru/electron-xiami#37]
![image](https://user-images.githubusercontent.com/21211353/40981964-cbe09b2e-690e-11e8-8027-e68fb71dc50e.png)

**Comment by eNkru** [comment]
这是另外一个已知的bug，被你发现了 LOL

**Comment by eNkru** [comment]
https://github.com/eNkru/electron-xiami/commit/bc49a305e2799a51f73112784806e140d76bda0b
应该是修复了这个问题。等我回家测试一下。

@Kexin-Li 你要是感兴趣，也可以测试一下。
