### ISSUE TITLE
电台不能播放

### ISSUE THREAD

**Issue by yaiba** [eNkru/electron-xiami#40]
couldn't load plugin,  应该是flash player 不能加载

**Comment by eNkru** [comment]
测试环境和APP版本？

**Comment by eNkru** [comment]
我的是10.13.5，试了1.5.0的打包版本，没有问题  ：（ 

这个issue先开着，看看有没有别人有相同的问题。

**Comment by eNkru** [comment]
@yaiba 你试试打包版本有没有问题？

**Comment by yaiba** [comment]
打包版本是指 Xiami.Music-1.5.0.dmg 么，我就是用的这个安装的

**Comment by eNkru** [comment]
@yaiba  估计是因为你用El Capitan的原因，封装的Flash插件可能不兼容你的macos版本。

有没有可能升级到High Sierra？ 如果不行的话，你可以自行替换你的OS的FLASH版本到下面的位置

`https://github.com/eNkru/electron-xiami/tree/develop/extraResources/pepperflash`

然后安装node，自行封装你的版本

```
npm i
npm run dist:macOS
```

然后会在dist目录下面看到你要的dmg安装包

**Comment by yaiba** [comment]
@eNkru 我还是算了吧，close了
