### ISSUE TITLE
壁纸？

### ISSUE THREAD

**Issue by pityhero233** [eNkru/electron-xiami#45]
想问您要一下readme里面osx那张港口的壁纸原图，google了半天没找到。 :P 
多谢！

**Comment by eNkru** [comment]
哈哈，还有这种需求。

我记得我在这里下载的。网盘里有很多，不过我不记得是哪个分辨率的了。你有带宽可以都下载下来

**Comment by pityhero233** [comment]
？？这里是哪里？？我没看到超链接呀

**Comment by eNkru** [comment]
@pityhero233 http://jwcyber.com/interfacelift/
忘记贴链接了，哈哈。SORRY
