### ISSUE TITLE
关于支持ubantu 18.04 LTS

### ISSUE THREAD

**Issue by octup** [eNkru/electron-xiami#46]
希望支持ubantu 18.04 LTS
![image](https://user-images.githubusercontent.com/37428564/44133090-4fc41d18-a090-11e8-81a3-016e51610511.png)
安装完成后
![image](https://user-images.githubusercontent.com/37428564/44133111-67ba65e4-a090-11e8-8f53-b62a590a1210.png)
我觉得像是图形显示不支持，但是我不知道怎么解决或者应该去哪里找解决方法，希望大佬指点

**Comment by eNkru** [comment]
我觉得你这个应该是网络问题，你看看 [虾米官方播放](https://www.xiami.com/play) 能访问么？

**Comment by octup** [comment]
懂得了 我去搞定网络
