### ISSUE TITLE
能否增加32位支持呢？

### ISSUE THREAD

**Issue by pasv0001** [eNkru/electron-xiami#47]
老电脑了，装的是32位系统，喜欢这个软件，但是安装不上。能否增加32位支持呢？非常感谢！！！

**Comment by eNkru** [comment]
你可以试着自己尝试编译一下。我手上现在没有32位系统。

你是什么系统，什么桌面？

**Comment by eNkru** [comment]
@pasv0001 

从现在这个版本会有32位系统的支持
[下载 1.5.1](https://github.com/eNkru/electron-xiami/releases/tag/v1.5.1)

感谢你的支持
