### ISSUE TITLE
deepin下dock图标问题

### ISSUE THREAD

**Issue by sunzongzheng** [eNkru/electron-xiami#50]
我从deepin商店下载的程序 图标正常
clone代码下来自行在mac下打包的程序在deepin下图标丢失

请问传到deepin商店的应用有特殊处理吗

**Comment by eNkru** [comment]
deepin的xwindow可能有他自己的设置，你看看DEEPIN自创建程序有没有设置图标的地方？

**Comment by sunzongzheng** [comment]
可能我没有描述清楚，从deepin商店下载的electron-xiami 图标是正常的，我自行clone master分支打包的图标不正常。请问deepin商店的版本是作者发的还是别人打包发的 :joy:

**Comment by eNkru** [comment]
我没有上传过DEEPIN商店，可能收录的人做了一些特别的设置。

如果不打包直接运行可能会找不到图标，打过包出问题目前还没有遇到过。

截屏看看什么样子？

**Comment by sunzongzheng** [comment]
![image](https://user-images.githubusercontent.com/12635613/46267761-59956100-c569-11e8-9e17-300f69c8bf52.png)
![image](https://user-images.githubusercontent.com/12635613/46267782-6b770400-c569-11e8-9c62-ee6b4794f68a.png)

**Comment by eNkru** [comment]
如果用APPIMAGE的话，也有这个问题么？

我手上没有deepin的系统，不好测试。最麻烦的办法就是手动改.desktop文件，指向可用的icon

**Comment by eNkru** [comment]
看一下ELECTRON-BUILDER有没有关于DEEPIN的特别选项，可以PULL REQUEST
