### ISSUE TITLE
ubuntu 16下无法登陆

### ISSUE THREAD

**Issue by Y-ncredible** [eNkru/electron-xiami#51]
RT，在ubuntu16下安装之后，点登录木有反应

**Comment by eNkru** [comment]
![image](https://user-images.githubusercontent.com/13460738/47318930-dec3ef80-d6a9-11e8-9eab-a4fba2bca5cb.png)

点击登录应该会出现这个界面，或许是你的网络的问题。你可以去 http://xiami.com/play 看一下有没有相同的问题

**Comment by eNkru** [comment]
如果还有问题的话，请重开ISSUE
