### ISSUE TITLE
Failed to query stereo recording

### ISSUE THREAD

**Issue by shangliy** [eNkru/electron-xiami#57]
启动后无法载入数据库.
[8323:1214/161711.089953:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.

System: Ubuntu 16.04
![screenshot from 2018-12-14 16-19-01](https://user-images.githubusercontent.com/14024100/50036214-1705f100-ffbc-11e8-8642-76067382fcd7.png)

**Comment by eNkru** [comment]
你试试这个链接能不能打开 @shangliy 

https://www.xiami.com/play

如果一样的话，那么就是你的地区被屏蔽了。我也在国外，是可以用虾米的。
