### ISSUE TITLE
Only a white screen when not online

### ISSUE THREAD

**Issue by probonopd** [eNkru/electron-xiami#58]
Application shows only a white screen when not connected to the internet.
Let's not assume people have internet connectivity all the time.

Reference: https://github.com/AppImage/appimage.github.io/pull/1120

---

应用程序在未连接到Internet时只显示白色屏幕。
我们不要假设人们一直都有互联网连接。

参考文献: https://github.com/AppImage/appimage.github.io/pull/1120

**Comment by eNkru** [comment]
之后会考虑加入这个功能测试

**Comment by eNkru** [comment]
@probonopd done as well :)
https://github.com/eNkru/electron-xiami/commit/3bcfc17a27fad565b998c094ea4fbaa97c933ffb

**Comment by probonopd** [comment]
Thank you. When will there be a new release for download?

**Comment by eNkru** [comment]
> Thank you. When will there be a new release for download?

https://github.com/eNkru/electron-xiami/releases/tag/v2.0.1
