### ISSUE TITLE
能否做个Windows版本的？

### ISSUE THREAD

**Issue by fuhmin** [eNkru/electron-xiami#60]
官方的Windows版本太差了，Linux装了这个看了下，挺好的。
希望能做个Windows版本，最好是UWP的。
感谢！

**Comment by eNkru** [comment]
这个是可以直接便宜成windows的版本 ：）

**Comment by fuhmin** [comment]
> 这个是可以直接便宜成windows的版本 ：）
> 之所以没有提供是因为虾米有官方的版本。我做的再好也没有官方API那种支持

感谢答复。
很抱歉我不是程序员，能否提供编译成exe或者UWP的方法？
我一般使用虾米APP的AI电台听音乐，而虾米官方的win客户端并没有，以至于我使用安卓模拟器运行虾米APP来听音乐O(∩_∩)O

**Comment by eNkru** [comment]
> > 这个是可以直接便宜成windows的版本 ：）
> > 之所以没有提供是因为虾米有官方的版本。我做的再好也没有官方API那种支持
> 
> 感谢答复。
> 很抱歉我不是程序员，能否提供编译成exe或者UWP的方法？
> 我一般使用虾米APP的AI电台听音乐，而虾米官方的win客户端并没有，以至于我使用安卓模拟器运行虾米APP来听音乐O(∩_∩)O

昨天想build一个来着，后来忙着忙着就忘了。
回去找台WINDOWS机器给你弄。现在手头上没有windows

**Comment by eNkru** [comment]
@fuhmin 
编译了一个MSI的安装包，你可以试一下。
https://github.com/eNkru/electron-xiami/releases/tag/v2.0.0-beta.2

**Comment by eNkru** [comment]
测试了一下，电台模式不可用因为没有打包WINDOWS的FLASH插件。虾米电台还在沿用FLASH版本也是没谁了。期待他们的新版可以放弃FLASH。

**Comment by fuhmin** [comment]
> 
> 
> 测试了一下，电台模式不可用因为没有打包WINDOWS的FLASH插件。虾米电台还在沿用FLASH版本也是没谁了。实在不想再打包一份FLASH进安装包。期待他们的新版电台

感谢!
发现虾米更新了新版本的Windows客户端，目前7.2.3版本。打包的而非原生Windows程序。
已经有电台可用了。但可能正如你所说，它们用了flash，操作起来感觉不流畅。
