### ISSUE TITLE
海外漫游支持请愿

### ISSUE THREAD

**Issue by Ben-Mao** [eNkru/electron-xiami#61]
现在虾米PC已经全面封禁海外用户了，但手机端其实还是支持VIP漫游7天的。老大能不能想办法支持下海外的苦难群众，做个客户端伪装什么的，救救虾米

**Comment by eNkru** [comment]
没有试过加国内代理会不会绕过海外限制。而且就算加上了代理，也很难找到一个合适的代理服务器吧
