### ISSUE TITLE
没有我的音乐选项，希望增加

### ISSUE THREAD

**Issue by scutzhe** [eNkru/electron-xiami#63]

**Comment by eNkru** [comment]
记得之前有的，可能页面改了class。回头给加上

**Comment by eNkru** [comment]
https://github.com/eNkru/electron-xiami/commit/33eb4d1c52cedcd2891c9b16e1d85ceb75e10bbd

这个版本还原了我的音乐和会员中心的菜单

**Comment by eNkru** [comment]
https://github.com/eNkru/electron-xiami/releases/tag/v2.0.1
