### ISSUE TITLE
登录后无法显示“我的音乐”，没法找到自己收藏的音乐

### ISSUE THREAD

**Issue by panpanpdj** [eNkru/electron-xiami#66]
登录后无法显示“我的音乐”，找不到自己收藏的音乐，重度虾米用户，这个不太方便，如果可以，希望能完善一下，谢谢啦！

**Comment by eNkru** [comment]
![image](https://user-images.githubusercontent.com/13460738/61341221-9c76ba00-a899-11e9-8048-61c4d0e46724.png)
我的音乐在右上角阿，你能截图看看吗？

**Comment by panpanpdj** [comment]
![深度截图_选择区域_20190717095123](https://user-images.githubusercontent.com/46858245/61341371-87d5fa00-a878-11e9-8fb8-95efbd1de812.png)
我尝试删除配置文件和缓存，还是不行

**Comment by eNkru** [comment]
你去官方网站登陆后有这些选项么？帮我截个图。顺便把网站的HTML也给我看看。
就看那个菜单那块就行

**Comment by panpanpdj** [comment]
![深度截图_选择区域_20190717100030](https://user-images.githubusercontent.com/46858245/61341631-b7d1cd00-a879-11e9-8214-83c062f09d96.png)
官方网站登录是有的，登录后的网站貌似也只是主站地址          https://www.xiami.com/
我用的这个是深度应用商店直接装的，我试下删掉从这里下载安装试试

**Comment by eNkru** [comment]
深度应用商店有可能没有更新版本，这个选项是今天发布的版本加上的
下载这个版本
https://github.com/eNkru/electron-xiami/releases/tag/v2.0.1

**Comment by panpanpdj** [comment]
正在下载，不过github的速度真是慢的令人发指，有国内的下载地址吗？确认了一下，深度商店的是2.0.0-beta.2版本的

**Comment by eNkru** [comment]
暂时没有哦，之前弄了一个GITEE后来不用，密码忘记了 ：（
下载好了，给个反馈哈

**Comment by panpanpdj** [comment]
在码云也看到了，不过貌似只有老版本，下载地址也是指向的github，下一半了，完了我装上试试

**Comment by panpanpdj** [comment]
![深度截图_选择区域_20190717110215](https://user-images.githubusercontent.com/46858245/61344024-5eba6700-a882-11e9-9b06-32c32b0d6ce3.png)
好了，谢谢啦！

**Comment by eNkru** [comment]
辛苦了，呵呵。我还不知道国内连接GITHUB超级慢。看来要找一个好点的发布渠道。
