### ISSUE TITLE
有个可能不该提的建议

### ISSUE THREAD

**Issue by sky5454** [eNkru/electron-xiami#67]
豆瓣FM那个功能比较简单，可以考虑集成一下。在虾米网页服务崩掉时可以用豆瓣FM

**Comment by eNkru** [comment]
阿哈，感谢你的建议。
一般连不上都是自身的网络有问题，和虾米无关啦。

当初做这个APP的初衷就是因为没有官方的LINUX客户端可以用。就不把两个APP混到一起了。
另外豆瓣FM我CRHOME上打不开。。

如果有机会可以做一个单独的app

```
Your connection is not private
Attackers might be trying to steal your information from fm.douban.com (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
```

**Comment by sky5454** [comment]
换个 DNS 试试，应该是被劫持了，我用的是 Chrome For Linux 最新版本
