### ISSUE TITLE
界面显示不正常，有很多方框

### ISSUE THREAD

**Issue by pasv0001** [eNkru/electron-xiami#68]
如题，我使用的是2.0.1_i386的版本，播放器窗口界面上，很多应该显示为图标的地方，比如播放按钮，下一曲按钮等，都是图片加载失败的那种方框。
这个版本的播放器非常棒，这点小bug能否改进下，谢谢你的付出！

**Comment by eNkru** [comment]
发个截图看看？还有你看官方的网页没有方框吗？
