### ISSUE TITLE
AppImage error

### ISSUE THREAD

**Issue by sonichy** [eNkru/electron-xiami#71]
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_electrBtLtxs/chrome-sandbox is owned by root and has mode 4755.
追踪与中断点陷阱

**Comment by eNkru** [comment]
this looks like a solution

https://github.com/electron/electron/issues/17972#issuecomment-486927073

**Comment by sonichy** [comment]
别人的AppImage怎么没问题？
https://github.com/xtuJSer/CoCoMusic/releases
