### ISSUE TITLE
能否添加桌面歌词？

### ISSUE THREAD

**Issue by redapple0204** [eNkru/electron-xiami#8]

**Comment by eNkru** [comment]
桌面歌词不难实现，可是同步歌词时间比较困难。
没找到监听快进跳转的JS代码。

谁找到了告诉我一下，看看能不能实现

**Comment by eNkru** [comment]
@redapple0204 
#13  1.0.5 版本增加了桌面歌词。
还在测试阶段，使用有问题欢迎开BUG报告 ：）
