### ISSUE TITLE
版面自适应出错 & 希望追加功能

### ISSUE THREAD

**Issue by SrvenX-07** [eNkru/electron-xiami#9]
<img width="508" alt="2018-01-10 5 43 29" src="https://user-images.githubusercontent.com/9426917/34765946-d0f4f10e-f62d-11e7-9034-c616e4045259.png">

1. 追加osx的媒体键控制支持
2. 建议再将UI简化一些

**Comment by eNkru** [comment]
“手机继续听”这个按钮估计没人会用到，下个版本会考虑去除。

**Comment by eNkru** [comment]
@SrvenX-07 设置里面可以设置成“只显示歌词列表”，界面会精简好多。

![image](https://user-images.githubusercontent.com/13460738/34801646-a9782294-f6ce-11e7-8447-6cac6256074c.png)

**Comment by eNkru** [comment]
这个app的初衷是做一个LINUX版本的虾米音乐客户端 （官方只提供了WINDOWS和MAC的版本）。
以后会考虑增加MAC的KEY和TOUCHBAR的支持。

**Comment by eNkru** [comment]
UI简化也有考虑 ：）比如说下面这个样子。

![image](https://user-images.githubusercontent.com/13460738/34802107-a8e10434-f6d0-11e7-9d6b-2152d2a8ea2b.png)

**Comment by eNkru** [comment]
隐藏了“手机继续听”按钮

新加了迷你模式

![image](https://user-images.githubusercontent.com/13460738/34849772-729ef97c-f788-11e7-85cc-f9fae26b1299.png)

#10 

MacOS键盘支持会另外开一个issue.

**Comment by eNkru** [comment]
#10
